plugins: [jekyll-paginate, jekyll-gist]
permalink: pretty
timezone: America/Los_Angeles
title: chandraonline
author:
name: 'Chandra Siva'
description: Learnings from my software development journey.
show_downloads: false
url: https://chandraonline.github.io
baseurl: /
repository: github.com/chandraonline/chandraonline.github.io

paginate: 5

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
